'use strict';

var colors = require('./');
console.log('bgblack:', colors.bgblack('some string'));
console.log('bgblue:', colors.bgblue('some string'));
console.log('bgcyan:', colors.bgcyan('some string'));
console.log('bggreen:', colors.bggreen('some string'));
console.log('bgmagenta:', colors.bgmagenta('some string'));
console.log('bgred:', colors.bgred('some string'));
console.log('bgwhite:', colors.bgwhite('some string'));
console.log('bgyellow:', colors.bgyellow('some string'));
console.log('black:', colors.black('some string'));
console.log('blue:', colors.blue('some string'));
console.log('bold:', colors.bold('some string'));
console.log('cyan:', colors.cyan('some string'));
console.log('dim:', colors.dim('some string'));
console.log('gray:', colors.gray('some string'));
console.log('green:', colors.green('some string'));
console.log('grey:', colors.grey('some string'));
console.log('hidden:', colors.hidden('some string'));
console.log('inverse:', colors.inverse('some string'));
console.log('italic:', colors.italic('some string'));
console.log('magenta:', colors.magenta('some string'));
console.log('red:', colors.red('some string'));
console.log('reset:', colors.reset('some string'));
console.log('strikethrough:', colors.strikethrough('some string'));
console.log('underline:', colors.underline('some string'));
console.log('white:', colors.white('some string'));
console.log('yellow:', colors.yellow('some string'));
